name: Deploy

on:
  workflow_run:
    workflows: [ "Check" ]
    types: [completed]
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "type-go-mongo-app"
          heroku_email: "whdygks210@naver.com"